FROM camptocamp/odoo-project:10.0-3.0.0-batteries

COPY . /odoo
RUN apt-get update \
    && apt-get install -y --no-install-recommends vim wget git
RUN pip install -r /odoo/requirements.txt
RUN pip install -e /odoo
RUN pip install -e /odoo/src
COPY /templates/odoo.cfg.tmpl /templates/odoo.cfg.tmpl

ENV ADDONS_PATH /odoo/src/addons,odoo/src/odoo/addons,/odoo/links,/odoo/external-src/odoo-shopinvader,/odoo/external-src/connector-search-engine,/odoo/external-src/bank-payment,/odoo/external-src/product-brand,/odoo/external-src/rest-framework,/odoo/external-src/sale-workflow,/odoo/external-src/queue,/odoo/external-src/product-variant,/odoo/external-src/server-tools,/odoo/external-src/delivery-carrier,/odoo/external-src/payment-gateway,/odoo/external-src/storage,/odoo/external-src/connector,/odoo/external-src/e-commerce,/odoo/external-src/ak-odoo-incubator,/odoo/external-src/crm
